// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whiteboard/v1/protocol.proto

package whiteboardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED         ErrorCode = 0
	ErrorCode_ERROR_CODE_BAD_REQUEST         ErrorCode = 1
	ErrorCode_ERROR_CODE_UNSUPPORTED_VERSION ErrorCode = 2
	// Another live connection on this board uses the same client_id.
	ErrorCode_ERROR_CODE_CLIENT_ID_IN_USE ErrorCode = 3
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_BAD_REQUEST",
		2: "ERROR_CODE_UNSUPPORTED_VERSION",
		3: "ERROR_CODE_CLIENT_ID_IN_USE",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":         0,
		"ERROR_CODE_BAD_REQUEST":         1,
		"ERROR_CODE_UNSUPPORTED_VERSION": 2,
		"ERROR_CODE_CLIENT_ID_IN_USE":    3,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_whiteboard_v1_protocol_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_whiteboard_v1_protocol_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{0}
}

type ShapeType int32

const (
	ShapeType_SHAPE_TYPE_UNSPECIFIED ShapeType = 0
	ShapeType_SHAPE_TYPE_RECT        ShapeType = 1
	ShapeType_SHAPE_TYPE_ELLIPSE     ShapeType = 2
	ShapeType_SHAPE_TYPE_STICKY      ShapeType = 3
	ShapeType_SHAPE_TYPE_TEXT        ShapeType = 4
	ShapeType_SHAPE_TYPE_ARROW       ShapeType = 5
	ShapeType_SHAPE_TYPE_FREEHAND    ShapeType = 6
)

// Enum value maps for ShapeType.
var (
	ShapeType_name = map[int32]string{
		0: "SHAPE_TYPE_UNSPECIFIED",
		1: "SHAPE_TYPE_RECT",
		2: "SHAPE_TYPE_ELLIPSE",
		3: "SHAPE_TYPE_STICKY",
		4: "SHAPE_TYPE_TEXT",
		5: "SHAPE_TYPE_ARROW",
		6: "SHAPE_TYPE_FREEHAND",
	}
	ShapeType_value = map[string]int32{
		"SHAPE_TYPE_UNSPECIFIED": 0,
		"SHAPE_TYPE_RECT":        1,
		"SHAPE_TYPE_ELLIPSE":     2,
		"SHAPE_TYPE_STICKY":      3,
		"SHAPE_TYPE_TEXT":        4,
		"SHAPE_TYPE_ARROW":       5,
		"SHAPE_TYPE_FREEHAND":    6,
	}
)

func (x ShapeType) Enum() *ShapeType {
	p := new(ShapeType)
	*p = x
	return p
}

func (x ShapeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShapeType) Descriptor() protoreflect.EnumDescriptor {
	return file_whiteboard_v1_protocol_proto_enumTypes[1].Descriptor()
}

func (ShapeType) Type() protoreflect.EnumType {
	return &file_whiteboard_v1_protocol_proto_enumTypes[1]
}

func (x ShapeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShapeType.Descriptor instead.
func (ShapeType) EnumDescriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{1}
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientMessage_Hello
	//	*ClientMessage_TimePing
	//	*ClientMessage_OpBatch
	Msg           isClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetMsg() isClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientMessage) GetTimePing() *TimePing {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_TimePing); ok {
			return x.TimePing
		}
	}
	return nil
}

func (x *ClientMessage) GetOpBatch() *OpBatch {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_OpBatch); ok {
			return x.OpBatch
		}
	}
	return nil
}

type isClientMessage_Msg interface {
	isClientMessage_Msg()
}

type ClientMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientMessage_TimePing struct {
	TimePing *TimePing `protobuf:"bytes,2,opt,name=time_ping,json=timePing,proto3,oneof"`
}

type ClientMessage_OpBatch struct {
	OpBatch *OpBatch `protobuf:"bytes,3,opt,name=op_batch,json=opBatch,proto3,oneof"`
}

func (*ClientMessage_Hello) isClientMessage_Msg() {}

func (*ClientMessage_TimePing) isClientMessage_Msg() {}

func (*ClientMessage_OpBatch) isClientMessage_Msg() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_Welcome
	//	*ServerMessage_TimePong
	//	*ServerMessage_Error
	//	*ServerMessage_Frame
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerMessage) GetTimePong() *TimePong {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_TimePong); ok {
			return x.TimePong
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *ServerError {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerMessage) GetFrame() *Frame {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ServerMessage_TimePong struct {
	TimePong *TimePong `protobuf:"bytes,2,opt,name=time_pong,json=timePong,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *ServerError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ServerMessage_Frame struct {
	Frame *Frame `protobuf:"bytes,4,opt,name=frame,proto3,oneof"`
}

func (*ServerMessage_Welcome) isServerMessage_Msg() {}

func (*ServerMessage_TimePong) isServerMessage_Msg() {}

func (*ServerMessage_Error) isServerMessage_Msg() {}

func (*ServerMessage_Frame) isServerMessage_Msg() {}

// First message on every connection.
type Hello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	BoardId         string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	// Random per client session, in [1, 2^53). Objects this client creates
	// have ids prefixed with its base-36 form (see ObjectIdPrefix).
	ClientId      uint64 `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *Hello) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type Welcome struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ServerTimeMs    int64                  `protobuf:"varint,3,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	// The board as of seq. Frames that follow carry batches with higher seqs.
	Seq     uint64         `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Objects []*ObjectState `protobuf:"bytes,5,rep,name=objects,proto3" json:"objects,omitempty"`
	// Highest OpBatch.client_seq already applied for this client_id, so a
	// reconnecting client knows which pending batches to drop and which to resend.
	LastClientSeq uint64 `protobuf:"varint,6,opt,name=last_client_seq,json=lastClientSeq,proto3" json:"last_client_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *Welcome) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Welcome) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Welcome) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *Welcome) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Welcome) GetObjects() []*ObjectState {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *Welcome) GetLastClientSeq() uint64 {
	if x != nil {
		return x.LastClientSeq
	}
	return 0
}

// Clock-offset and RTT probe. The server echoes t0 and adds its own clock.
type TimePing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T0            float64                `protobuf:"fixed64,1,opt,name=t0,proto3" json:"t0,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimePing) Reset() {
	*x = TimePing{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimePing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimePing) ProtoMessage() {}

func (x *TimePing) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimePing.ProtoReflect.Descriptor instead.
func (*TimePing) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *TimePing) GetT0() float64 {
	if x != nil {
		return x.T0
	}
	return 0
}

type TimePong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T0            float64                `protobuf:"fixed64,1,opt,name=t0,proto3" json:"t0,omitempty"`
	ServerTimeMs  int64                  `protobuf:"varint,2,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimePong) Reset() {
	*x = TimePong{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimePong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimePong) ProtoMessage() {}

func (x *TimePong) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimePong.ProtoReflect.Descriptor instead.
func (*TimePong) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *TimePong) GetT0() float64 {
	if x != nil {
		return x.T0
	}
	return 0
}

func (x *TimePong) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

type ServerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=whiteboard.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerError) Reset() {
	*x = ServerError{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerError) ProtoMessage() {}

func (x *ServerError) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerError.ProtoReflect.Descriptor instead.
func (*ServerError) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *ServerError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ServerError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Hybrid logical clock timestamp, totally ordered by (wall_ms, counter, client_id).
type Stamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WallMs        int64                  `protobuf:"varint,1,opt,name=wall_ms,json=wallMs,proto3" json:"wall_ms,omitempty"`
	Counter       uint32                 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	ClientId      uint64                 `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stamp) Reset() {
	*x = Stamp{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stamp) ProtoMessage() {}

func (x *Stamp) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stamp.ProtoReflect.Descriptor instead.
func (*Stamp) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *Stamp) GetWallMs() int64 {
	if x != nil {
		return x.WallMs
	}
	return 0
}

func (x *Stamp) GetCounter() uint32 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *Stamp) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

// Field numbers must stay below 32: FieldStamps uses them as bit positions.
type ObjectProps struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Set once, when the object is created.
	Type    *ShapeType `protobuf:"varint,1,opt,name=type,proto3,enum=whiteboard.v1.ShapeType,oneof" json:"type,omitempty"`
	Deleted *bool      `protobuf:"varint,2,opt,name=deleted,proto3,oneof" json:"deleted,omitempty"`
	X       *float64   `protobuf:"fixed64,3,opt,name=x,proto3,oneof" json:"x,omitempty"`
	Y       *float64   `protobuf:"fixed64,4,opt,name=y,proto3,oneof" json:"y,omitempty"`
	W       *float64   `protobuf:"fixed64,5,opt,name=w,proto3,oneof" json:"w,omitempty"`
	H       *float64   `protobuf:"fixed64,6,opt,name=h,proto3,oneof" json:"h,omitempty"`
	// Fractional index; objects render in (z, id) order.
	Z *string `protobuf:"bytes,7,opt,name=z,proto3,oneof" json:"z,omitempty"`
	// 0xRRGGBBAA.
	Fill          *uint32  `protobuf:"varint,8,opt,name=fill,proto3,oneof" json:"fill,omitempty"`
	Stroke        *uint32  `protobuf:"varint,9,opt,name=stroke,proto3,oneof" json:"stroke,omitempty"`
	StrokeWidth   *float32 `protobuf:"fixed32,10,opt,name=stroke_width,json=strokeWidth,proto3,oneof" json:"stroke_width,omitempty"`
	Text          *string  `protobuf:"bytes,11,opt,name=text,proto3,oneof" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectProps) Reset() {
	*x = ObjectProps{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectProps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectProps) ProtoMessage() {}

func (x *ObjectProps) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectProps.ProtoReflect.Descriptor instead.
func (*ObjectProps) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *ObjectProps) GetType() ShapeType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ShapeType_SHAPE_TYPE_UNSPECIFIED
}

func (x *ObjectProps) GetDeleted() bool {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return false
}

func (x *ObjectProps) GetX() float64 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *ObjectProps) GetY() float64 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *ObjectProps) GetW() float64 {
	if x != nil && x.W != nil {
		return *x.W
	}
	return 0
}

func (x *ObjectProps) GetH() float64 {
	if x != nil && x.H != nil {
		return *x.H
	}
	return 0
}

func (x *ObjectProps) GetZ() string {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return ""
}

func (x *ObjectProps) GetFill() uint32 {
	if x != nil && x.Fill != nil {
		return *x.Fill
	}
	return 0
}

func (x *ObjectProps) GetStroke() uint32 {
	if x != nil && x.Stroke != nil {
		return *x.Stroke
	}
	return 0
}

func (x *ObjectProps) GetStrokeWidth() float32 {
	if x != nil && x.StrokeWidth != nil {
		return *x.StrokeWidth
	}
	return 0
}

func (x *ObjectProps) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

// Sets every property present in props, all with the batch's stamp.
// An op on an unknown id creates the object and must set type.
type Op struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Props         *ObjectProps           `protobuf:"bytes,2,opt,name=props,proto3" json:"props,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Op) Reset() {
	*x = Op{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Op.ProtoReflect.Descriptor instead.
func (*Op) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *Op) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Op) GetProps() *ObjectProps {
	if x != nil {
		return x.Props
	}
	return nil
}

// One user action (e.g. dragging three shapes), applied atomically.
type OpBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per client, starting at 1 and increasing by 1.
	ClientSeq uint64 `protobuf:"varint,1,opt,name=client_seq,json=clientSeq,proto3" json:"client_seq,omitempty"`
	// client_id is ignored; the server uses the connection's.
	Stamp         *Stamp `protobuf:"bytes,2,opt,name=stamp,proto3" json:"stamp,omitempty"`
	Ops           []*Op  `protobuf:"bytes,3,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpBatch) Reset() {
	*x = OpBatch{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpBatch) ProtoMessage() {}

func (x *OpBatch) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpBatch.ProtoReflect.Descriptor instead.
func (*OpBatch) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *OpBatch) GetClientSeq() uint64 {
	if x != nil {
		return x.ClientSeq
	}
	return 0
}

func (x *OpBatch) GetStamp() *Stamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *OpBatch) GetOps() []*Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

// A batch as ordered by the board. stamp.client_id is the origin client.
type SequencedBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Stamp         *Stamp                 `protobuf:"bytes,2,opt,name=stamp,proto3" json:"stamp,omitempty"`
	Ops           []*Op                  `protobuf:"bytes,3,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequencedBatch) Reset() {
	*x = SequencedBatch{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequencedBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequencedBatch) ProtoMessage() {}

func (x *SequencedBatch) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequencedBatch.ProtoReflect.Descriptor instead.
func (*SequencedBatch) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *SequencedBatch) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SequencedBatch) GetStamp() *Stamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *SequencedBatch) GetOps() []*Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

type Ack struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ClientSeq uint64                 `protobuf:"varint,1,opt,name=client_seq,json=clientSeq,proto3" json:"client_seq,omitempty"`
	// Zero when rejected.
	Seq uint64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// The stamp the batch was applied with. It differs from the one sent only
	// if the server clamped a stamp too far in the future; the client must then resync.
	Stamp *Stamp `protobuf:"bytes,3,opt,name=stamp,proto3" json:"stamp,omitempty"`
	// The batch failed validation and was not applied; the client must resync.
	Rejected      bool   `protobuf:"varint,4,opt,name=rejected,proto3" json:"rejected,omitempty"`
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *Ack) GetClientSeq() uint64 {
	if x != nil {
		return x.ClientSeq
	}
	return 0
}

func (x *Ack) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Ack) GetStamp() *Stamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *Ack) GetRejected() bool {
	if x != nil {
		return x.Rejected
	}
	return false
}

func (x *Ack) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Everything a client needs from one board tick: other clients' batches, in
// seq order, and acks for its own.
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batches       []*SequencedBatch      `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	Acks          []*Ack                 `protobuf:"bytes,2,rep,name=acks,proto3" json:"acks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *Frame) GetBatches() []*SequencedBatch {
	if x != nil {
		return x.Batches
	}
	return nil
}

func (x *Frame) GetAcks() []*Ack {
	if x != nil {
		return x.Acks
	}
	return nil
}

type ObjectState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Props         *ObjectProps           `protobuf:"bytes,2,opt,name=props,proto3" json:"props,omitempty"`
	Stamps        []*FieldStamps         `protobuf:"bytes,3,rep,name=stamps,proto3" json:"stamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectState) Reset() {
	*x = ObjectState{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectState) ProtoMessage() {}

func (x *ObjectState) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectState.ProtoReflect.Descriptor instead.
func (*ObjectState) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *ObjectState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectState) GetProps() *ObjectProps {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *ObjectState) GetStamps() []*FieldStamps {
	if x != nil {
		return x.Stamps
	}
	return nil
}

// The stamp of every property whose field number's bit is set in field_mask.
type FieldStamps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stamp         *Stamp                 `protobuf:"bytes,1,opt,name=stamp,proto3" json:"stamp,omitempty"`
	FieldMask     uint32                 `protobuf:"varint,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldStamps) Reset() {
	*x = FieldStamps{}
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldStamps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldStamps) ProtoMessage() {}

func (x *FieldStamps) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldStamps.ProtoReflect.Descriptor instead.
func (*FieldStamps) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *FieldStamps) GetStamp() *Stamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *FieldStamps) GetFieldMask() uint32 {
	if x != nil {
		return x.FieldMask
	}
	return 0
}

var File_whiteboard_v1_protocol_proto protoreflect.FileDescriptor

const file_whiteboard_v1_protocol_proto_rawDesc = "" +
	"\n" +
	"\x1cwhiteboard/v1/protocol.proto\x12\rwhiteboard.v1\"\xb1\x01\n" +
	"\rClientMessage\x12,\n" +
	"\x05hello\x18\x01 \x01(\v2\x14.whiteboard.v1.HelloH\x00R\x05hello\x126\n" +
	"\ttime_ping\x18\x02 \x01(\v2\x17.whiteboard.v1.TimePingH\x00R\btimePing\x123\n" +
	"\bop_batch\x18\x03 \x01(\v2\x16.whiteboard.v1.OpBatchH\x00R\aopBatchB\x05\n" +
	"\x03msg\"\xe4\x01\n" +
	"\rServerMessage\x122\n" +
	"\awelcome\x18\x01 \x01(\v2\x16.whiteboard.v1.WelcomeH\x00R\awelcome\x126\n" +
	"\ttime_pong\x18\x02 \x01(\v2\x17.whiteboard.v1.TimePongH\x00R\btimePong\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x1a.whiteboard.v1.ServerErrorH\x00R\x05error\x12,\n" +
	"\x05frame\x18\x04 \x01(\v2\x14.whiteboard.v1.FrameH\x00R\x05frameB\x05\n" +
	"\x03msg\"j\n" +
	"\x05Hello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x04R\bclientId\"\xe3\x01\n" +
	"\aWelcome\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12$\n" +
	"\x0eserver_time_ms\x18\x03 \x01(\x03R\fserverTimeMs\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x124\n" +
	"\aobjects\x18\x05 \x03(\v2\x1a.whiteboard.v1.ObjectStateR\aobjects\x12&\n" +
	"\x0flast_client_seq\x18\x06 \x01(\x04R\rlastClientSeq\"\x1a\n" +
	"\bTimePing\x12\x0e\n" +
	"\x02t0\x18\x01 \x01(\x01R\x02t0\"@\n" +
	"\bTimePong\x12\x0e\n" +
	"\x02t0\x18\x01 \x01(\x01R\x02t0\x12$\n" +
	"\x0eserver_time_ms\x18\x02 \x01(\x03R\fserverTimeMs\"U\n" +
	"\vServerError\x12,\n" +
	"\x04code\x18\x01 \x01(\x0e2\x18.whiteboard.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\x05Stamp\x12\x17\n" +
	"\awall_ms\x18\x01 \x01(\x03R\x06wallMs\x12\x18\n" +
	"\acounter\x18\x02 \x01(\rR\acounter\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x04R\bclientId\"\x96\x03\n" +
	"\vObjectProps\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.whiteboard.v1.ShapeTypeH\x00R\x04type\x88\x01\x01\x12\x1d\n" +
	"\adeleted\x18\x02 \x01(\bH\x01R\adeleted\x88\x01\x01\x12\x11\n" +
	"\x01x\x18\x03 \x01(\x01H\x02R\x01x\x88\x01\x01\x12\x11\n" +
	"\x01y\x18\x04 \x01(\x01H\x03R\x01y\x88\x01\x01\x12\x11\n" +
	"\x01w\x18\x05 \x01(\x01H\x04R\x01w\x88\x01\x01\x12\x11\n" +
	"\x01h\x18\x06 \x01(\x01H\x05R\x01h\x88\x01\x01\x12\x11\n" +
	"\x01z\x18\a \x01(\tH\x06R\x01z\x88\x01\x01\x12\x17\n" +
	"\x04fill\x18\b \x01(\rH\aR\x04fill\x88\x01\x01\x12\x1b\n" +
	"\x06stroke\x18\t \x01(\rH\bR\x06stroke\x88\x01\x01\x12&\n" +
	"\fstroke_width\x18\n" +
	" \x01(\x02H\tR\vstrokeWidth\x88\x01\x01\x12\x17\n" +
	"\x04text\x18\v \x01(\tH\n" +
	"R\x04text\x88\x01\x01B\a\n" +
	"\x05_typeB\n" +
	"\n" +
	"\b_deletedB\x04\n" +
	"\x02_xB\x04\n" +
	"\x02_yB\x04\n" +
	"\x02_wB\x04\n" +
	"\x02_hB\x04\n" +
	"\x02_zB\a\n" +
	"\x05_fillB\t\n" +
	"\a_strokeB\x0f\n" +
	"\r_stroke_widthB\a\n" +
	"\x05_text\"F\n" +
	"\x02Op\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x05props\x18\x02 \x01(\v2\x1a.whiteboard.v1.ObjectPropsR\x05props\"y\n" +
	"\aOpBatch\x12\x1d\n" +
	"\n" +
	"client_seq\x18\x01 \x01(\x04R\tclientSeq\x12*\n" +
	"\x05stamp\x18\x02 \x01(\v2\x14.whiteboard.v1.StampR\x05stamp\x12#\n" +
	"\x03ops\x18\x03 \x03(\v2\x11.whiteboard.v1.OpR\x03ops\"s\n" +
	"\x0eSequencedBatch\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12*\n" +
	"\x05stamp\x18\x02 \x01(\v2\x14.whiteboard.v1.StampR\x05stamp\x12#\n" +
	"\x03ops\x18\x03 \x03(\v2\x11.whiteboard.v1.OpR\x03ops\"\x96\x01\n" +
	"\x03Ack\x12\x1d\n" +
	"\n" +
	"client_seq\x18\x01 \x01(\x04R\tclientSeq\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12*\n" +
	"\x05stamp\x18\x03 \x01(\v2\x14.whiteboard.v1.StampR\x05stamp\x12\x1a\n" +
	"\brejected\x18\x04 \x01(\bR\brejected\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"h\n" +
	"\x05Frame\x127\n" +
	"\abatches\x18\x01 \x03(\v2\x1d.whiteboard.v1.SequencedBatchR\abatches\x12&\n" +
	"\x04acks\x18\x02 \x03(\v2\x12.whiteboard.v1.AckR\x04acks\"\x83\x01\n" +
	"\vObjectState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x05props\x18\x02 \x01(\v2\x1a.whiteboard.v1.ObjectPropsR\x05props\x122\n" +
	"\x06stamps\x18\x03 \x03(\v2\x1a.whiteboard.v1.FieldStampsR\x06stamps\"X\n" +
	"\vFieldStamps\x12*\n" +
	"\x05stamp\x18\x01 \x01(\v2\x14.whiteboard.v1.StampR\x05stamp\x12\x1d\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\rR\tfieldMask*\x88\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ERROR_CODE_BAD_REQUEST\x10\x01\x12\"\n" +
	"\x1eERROR_CODE_UNSUPPORTED_VERSION\x10\x02\x12\x1f\n" +
	"\x1bERROR_CODE_CLIENT_ID_IN_USE\x10\x03*\xaf\x01\n" +
	"\tShapeType\x12\x1a\n" +
	"\x16SHAPE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSHAPE_TYPE_RECT\x10\x01\x12\x16\n" +
	"\x12SHAPE_TYPE_ELLIPSE\x10\x02\x12\x15\n" +
	"\x11SHAPE_TYPE_STICKY\x10\x03\x12\x13\n" +
	"\x0fSHAPE_TYPE_TEXT\x10\x04\x12\x14\n" +
	"\x10SHAPE_TYPE_ARROW\x10\x05\x12\x17\n" +
	"\x13SHAPE_TYPE_FREEHAND\x10\x06B\xaa\x01\n" +
	"\x11com.whiteboard.v1B\rProtocolProtoP\x01Z1whiteboard/internal/pb/whiteboard/v1;whiteboardv1\xa2\x02\x03WXX\xaa\x02\rWhiteboard.V1\xca\x02\rWhiteboard\\V1\xe2\x02\x19Whiteboard\\V1\\GPBMetadata\xea\x02\x0eWhiteboard::V1b\x06proto3"

var (
	file_whiteboard_v1_protocol_proto_rawDescOnce sync.Once
	file_whiteboard_v1_protocol_proto_rawDescData []byte
)

func file_whiteboard_v1_protocol_proto_rawDescGZIP() []byte {
	file_whiteboard_v1_protocol_proto_rawDescOnce.Do(func() {
		file_whiteboard_v1_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whiteboard_v1_protocol_proto_rawDesc), len(file_whiteboard_v1_protocol_proto_rawDesc)))
	})
	return file_whiteboard_v1_protocol_proto_rawDescData
}

var file_whiteboard_v1_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_whiteboard_v1_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_whiteboard_v1_protocol_proto_goTypes = []any{
	(ErrorCode)(0),         // 0: whiteboard.v1.ErrorCode
	(ShapeType)(0),         // 1: whiteboard.v1.ShapeType
	(*ClientMessage)(nil),  // 2: whiteboard.v1.ClientMessage
	(*ServerMessage)(nil),  // 3: whiteboard.v1.ServerMessage
	(*Hello)(nil),          // 4: whiteboard.v1.Hello
	(*Welcome)(nil),        // 5: whiteboard.v1.Welcome
	(*TimePing)(nil),       // 6: whiteboard.v1.TimePing
	(*TimePong)(nil),       // 7: whiteboard.v1.TimePong
	(*ServerError)(nil),    // 8: whiteboard.v1.ServerError
	(*Stamp)(nil),          // 9: whiteboard.v1.Stamp
	(*ObjectProps)(nil),    // 10: whiteboard.v1.ObjectProps
	(*Op)(nil),             // 11: whiteboard.v1.Op
	(*OpBatch)(nil),        // 12: whiteboard.v1.OpBatch
	(*SequencedBatch)(nil), // 13: whiteboard.v1.SequencedBatch
	(*Ack)(nil),            // 14: whiteboard.v1.Ack
	(*Frame)(nil),          // 15: whiteboard.v1.Frame
	(*ObjectState)(nil),    // 16: whiteboard.v1.ObjectState
	(*FieldStamps)(nil),    // 17: whiteboard.v1.FieldStamps
}
var file_whiteboard_v1_protocol_proto_depIdxs = []int32{
	4,  // 0: whiteboard.v1.ClientMessage.hello:type_name -> whiteboard.v1.Hello
	6,  // 1: whiteboard.v1.ClientMessage.time_ping:type_name -> whiteboard.v1.TimePing
	12, // 2: whiteboard.v1.ClientMessage.op_batch:type_name -> whiteboard.v1.OpBatch
	5,  // 3: whiteboard.v1.ServerMessage.welcome:type_name -> whiteboard.v1.Welcome
	7,  // 4: whiteboard.v1.ServerMessage.time_pong:type_name -> whiteboard.v1.TimePong
	8,  // 5: whiteboard.v1.ServerMessage.error:type_name -> whiteboard.v1.ServerError
	15, // 6: whiteboard.v1.ServerMessage.frame:type_name -> whiteboard.v1.Frame
	16, // 7: whiteboard.v1.Welcome.objects:type_name -> whiteboard.v1.ObjectState
	0,  // 8: whiteboard.v1.ServerError.code:type_name -> whiteboard.v1.ErrorCode
	1,  // 9: whiteboard.v1.ObjectProps.type:type_name -> whiteboard.v1.ShapeType
	10, // 10: whiteboard.v1.Op.props:type_name -> whiteboard.v1.ObjectProps
	9,  // 11: whiteboard.v1.OpBatch.stamp:type_name -> whiteboard.v1.Stamp
	11, // 12: whiteboard.v1.OpBatch.ops:type_name -> whiteboard.v1.Op
	9,  // 13: whiteboard.v1.SequencedBatch.stamp:type_name -> whiteboard.v1.Stamp
	11, // 14: whiteboard.v1.SequencedBatch.ops:type_name -> whiteboard.v1.Op
	9,  // 15: whiteboard.v1.Ack.stamp:type_name -> whiteboard.v1.Stamp
	13, // 16: whiteboard.v1.Frame.batches:type_name -> whiteboard.v1.SequencedBatch
	14, // 17: whiteboard.v1.Frame.acks:type_name -> whiteboard.v1.Ack
	10, // 18: whiteboard.v1.ObjectState.props:type_name -> whiteboard.v1.ObjectProps
	17, // 19: whiteboard.v1.ObjectState.stamps:type_name -> whiteboard.v1.FieldStamps
	9,  // 20: whiteboard.v1.FieldStamps.stamp:type_name -> whiteboard.v1.Stamp
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_whiteboard_v1_protocol_proto_init() }
func file_whiteboard_v1_protocol_proto_init() {
	if File_whiteboard_v1_protocol_proto != nil {
		return
	}
	file_whiteboard_v1_protocol_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Hello)(nil),
		(*ClientMessage_TimePing)(nil),
		(*ClientMessage_OpBatch)(nil),
	}
	file_whiteboard_v1_protocol_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Welcome)(nil),
		(*ServerMessage_TimePong)(nil),
		(*ServerMessage_Error)(nil),
		(*ServerMessage_Frame)(nil),
	}
	file_whiteboard_v1_protocol_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whiteboard_v1_protocol_proto_rawDesc), len(file_whiteboard_v1_protocol_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whiteboard_v1_protocol_proto_goTypes,
		DependencyIndexes: file_whiteboard_v1_protocol_proto_depIdxs,
		EnumInfos:         file_whiteboard_v1_protocol_proto_enumTypes,
		MessageInfos:      file_whiteboard_v1_protocol_proto_msgTypes,
	}.Build()
	File_whiteboard_v1_protocol_proto = out.File
	file_whiteboard_v1_protocol_proto_goTypes = nil
	file_whiteboard_v1_protocol_proto_depIdxs = nil
}
