// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whiteboard/v1/storage.proto

package whiteboardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A full board as of seq, stored zstd-compressed in the snapshots table.
type BoardSnapshot struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Seq     uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Objects []*ObjectState         `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	// Highest client_seq applied per client, so resends after a restart are
	// still recognized as duplicates.
	Clients       []*ClientProgress `protobuf:"bytes,3,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardSnapshot) Reset() {
	*x = BoardSnapshot{}
	mi := &file_whiteboard_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardSnapshot) ProtoMessage() {}

func (x *BoardSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardSnapshot.ProtoReflect.Descriptor instead.
func (*BoardSnapshot) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *BoardSnapshot) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *BoardSnapshot) GetObjects() []*ObjectState {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *BoardSnapshot) GetClients() []*ClientProgress {
	if x != nil {
		return x.Clients
	}
	return nil
}

type ClientProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	LastClientSeq uint64                 `protobuf:"varint,2,opt,name=last_client_seq,json=lastClientSeq,proto3" json:"last_client_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientProgress) Reset() {
	*x = ClientProgress{}
	mi := &file_whiteboard_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientProgress) ProtoMessage() {}

func (x *ClientProgress) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientProgress.ProtoReflect.Descriptor instead.
func (*ClientProgress) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ClientProgress) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ClientProgress) GetLastClientSeq() uint64 {
	if x != nil {
		return x.LastClientSeq
	}
	return 0
}

// One sequenced batch as stored in the ops table (the seq and client
// columns live beside it).
type StoredBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stamp         *Stamp                 `protobuf:"bytes,1,opt,name=stamp,proto3" json:"stamp,omitempty"`
	Ops           []*Op                  `protobuf:"bytes,2,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredBatch) Reset() {
	*x = StoredBatch{}
	mi := &file_whiteboard_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredBatch) ProtoMessage() {}

func (x *StoredBatch) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredBatch.ProtoReflect.Descriptor instead.
func (*StoredBatch) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *StoredBatch) GetStamp() *Stamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *StoredBatch) GetOps() []*Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

// A run of log entries, stored zstd-compressed in op_segments once they are
// older than a snapshot (compaction; docs/decisions/0004-storage.md).
type LogSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SegmentEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSegment) Reset() {
	*x = LogSegment{}
	mi := &file_whiteboard_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSegment) ProtoMessage() {}

func (x *LogSegment) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSegment.ProtoReflect.Descriptor instead.
func (*LogSegment) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_storage_proto_rawDescGZIP(), []int{3}
}

func (x *LogSegment) GetEntries() []*SegmentEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SegmentEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ClientId      uint64                 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSeq     uint64                 `protobuf:"varint,3,opt,name=client_seq,json=clientSeq,proto3" json:"client_seq,omitempty"`
	Stamp         *Stamp                 `protobuf:"bytes,4,opt,name=stamp,proto3" json:"stamp,omitempty"`
	Ops           []*Op                  `protobuf:"bytes,5,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentEntry) Reset() {
	*x = SegmentEntry{}
	mi := &file_whiteboard_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentEntry) ProtoMessage() {}

func (x *SegmentEntry) ProtoReflect() protoreflect.Message {
	mi := &file_whiteboard_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentEntry.ProtoReflect.Descriptor instead.
func (*SegmentEntry) Descriptor() ([]byte, []int) {
	return file_whiteboard_v1_storage_proto_rawDescGZIP(), []int{4}
}

func (x *SegmentEntry) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SegmentEntry) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *SegmentEntry) GetClientSeq() uint64 {
	if x != nil {
		return x.ClientSeq
	}
	return 0
}

func (x *SegmentEntry) GetStamp() *Stamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *SegmentEntry) GetOps() []*Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

var File_whiteboard_v1_storage_proto protoreflect.FileDescriptor

const file_whiteboard_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x1bwhiteboard/v1/storage.proto\x12\rwhiteboard.v1\x1a\x1cwhiteboard/v1/protocol.proto\"\x90\x01\n" +
	"\rBoardSnapshot\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x124\n" +
	"\aobjects\x18\x02 \x03(\v2\x1a.whiteboard.v1.ObjectStateR\aobjects\x127\n" +
	"\aclients\x18\x03 \x03(\v2\x1d.whiteboard.v1.ClientProgressR\aclients\"U\n" +
	"\x0eClientProgress\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12&\n" +
	"\x0flast_client_seq\x18\x02 \x01(\x04R\rlastClientSeq\"^\n" +
	"\vStoredBatch\x12*\n" +
	"\x05stamp\x18\x01 \x01(\v2\x14.whiteboard.v1.StampR\x05stamp\x12#\n" +
	"\x03ops\x18\x02 \x03(\v2\x11.whiteboard.v1.OpR\x03ops\"C\n" +
	"\n" +
	"LogSegment\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.whiteboard.v1.SegmentEntryR\aentries\"\xad\x01\n" +
	"\fSegmentEntry\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x04R\bclientId\x12\x1d\n" +
	"\n" +
	"client_seq\x18\x03 \x01(\x04R\tclientSeq\x12*\n" +
	"\x05stamp\x18\x04 \x01(\v2\x14.whiteboard.v1.StampR\x05stamp\x12#\n" +
	"\x03ops\x18\x05 \x03(\v2\x11.whiteboard.v1.OpR\x03opsB\xa9\x01\n" +
	"\x11com.whiteboard.v1B\fStorageProtoP\x01Z1whiteboard/internal/pb/whiteboard/v1;whiteboardv1\xa2\x02\x03WXX\xaa\x02\rWhiteboard.V1\xca\x02\rWhiteboard\\V1\xe2\x02\x19Whiteboard\\V1\\GPBMetadata\xea\x02\x0eWhiteboard::V1b\x06proto3"

var (
	file_whiteboard_v1_storage_proto_rawDescOnce sync.Once
	file_whiteboard_v1_storage_proto_rawDescData []byte
)

func file_whiteboard_v1_storage_proto_rawDescGZIP() []byte {
	file_whiteboard_v1_storage_proto_rawDescOnce.Do(func() {
		file_whiteboard_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whiteboard_v1_storage_proto_rawDesc), len(file_whiteboard_v1_storage_proto_rawDesc)))
	})
	return file_whiteboard_v1_storage_proto_rawDescData
}

var file_whiteboard_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_whiteboard_v1_storage_proto_goTypes = []any{
	(*BoardSnapshot)(nil),  // 0: whiteboard.v1.BoardSnapshot
	(*ClientProgress)(nil), // 1: whiteboard.v1.ClientProgress
	(*StoredBatch)(nil),    // 2: whiteboard.v1.StoredBatch
	(*LogSegment)(nil),     // 3: whiteboard.v1.LogSegment
	(*SegmentEntry)(nil),   // 4: whiteboard.v1.SegmentEntry
	(*ObjectState)(nil),    // 5: whiteboard.v1.ObjectState
	(*Stamp)(nil),          // 6: whiteboard.v1.Stamp
	(*Op)(nil),             // 7: whiteboard.v1.Op
}
var file_whiteboard_v1_storage_proto_depIdxs = []int32{
	5, // 0: whiteboard.v1.BoardSnapshot.objects:type_name -> whiteboard.v1.ObjectState
	1, // 1: whiteboard.v1.BoardSnapshot.clients:type_name -> whiteboard.v1.ClientProgress
	6, // 2: whiteboard.v1.StoredBatch.stamp:type_name -> whiteboard.v1.Stamp
	7, // 3: whiteboard.v1.StoredBatch.ops:type_name -> whiteboard.v1.Op
	4, // 4: whiteboard.v1.LogSegment.entries:type_name -> whiteboard.v1.SegmentEntry
	6, // 5: whiteboard.v1.SegmentEntry.stamp:type_name -> whiteboard.v1.Stamp
	7, // 6: whiteboard.v1.SegmentEntry.ops:type_name -> whiteboard.v1.Op
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_whiteboard_v1_storage_proto_init() }
func file_whiteboard_v1_storage_proto_init() {
	if File_whiteboard_v1_storage_proto != nil {
		return
	}
	file_whiteboard_v1_protocol_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whiteboard_v1_storage_proto_rawDesc), len(file_whiteboard_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whiteboard_v1_storage_proto_goTypes,
		DependencyIndexes: file_whiteboard_v1_storage_proto_depIdxs,
		MessageInfos:      file_whiteboard_v1_storage_proto_msgTypes,
	}.Build()
	File_whiteboard_v1_storage_proto = out.File
	file_whiteboard_v1_storage_proto_goTypes = nil
	file_whiteboard_v1_storage_proto_depIdxs = nil
}
